# Generated by Django 2.2.2 on 2019-06-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_boy', '0002_auto_20190623_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
