# Generated by Django 2.2.2 on 2019-06-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_boy', '0006_auto_20190625_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
