# Generated by Django 2.2.2 on 2019-06-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea_boy', '0007_auto_20190625_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
